describe('DLC Settings', () => {
	beforeEach(() => {
		cy.visit('/p5/settings')
	})
	it('adds Ariadne to the compendium', () => {
		cy.get('[data-cy="Ariadne"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Beast Weaver')
	})
	it('adds Asterius to the compendium', () => {
		cy.get('[data-cy="Asterius"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Asterius')
		cy.get('.table-div').should('contain', 'Asterius')
		cy.get('.table-div').should('contain', 'Asterius Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Titanomachia')
	})
	it('adds Izanagi to the compendium', () => {
		cy.get('[data-cy="Izanagi"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Izanagi')
		cy.get('.table-div').should('contain', 'Izanagi Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Cross Slash')
	})
	it('adds Kaguya to the compendium', () => {
		cy.get('[data-cy="Kaguya"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Kaguya')
		cy.get('.table-div').should('contain', 'Kaguya Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Shining Arrows')
	})
	it('adds Magatsu-Izanagi to the compendium', () => {
		cy.get('[data-cy="Magatsu-Izanagi"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Magatsu-Izanagi')
		cy.get('.table-div').should('contain', 'Magatsu-Izanagi Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Magatsu Mandala')
	})
	it('adds Messiah to the compendium', () => {
		cy.get('[data-cy="Messiah"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Messiah')
		cy.get('.table-div').should('contain', 'Messiah Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Oratorio')
	})
	it('adds Orpheus to the compendium', () => {
		cy.get('[data-cy="Orpheus"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Orpheus')
		cy.get('.table-div').should('contain', 'Orpheus Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Cadenza')
	})
	it('adds Thanatos to the compendium', () => {
		cy.get('[data-cy="Thanatos"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Thanatos')
		cy.get('.table-div').should('contain', 'Thanatos Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Door of Hades')
	})
	it('adds Tsukiyomi to the compendium', () => {
		cy.get('[data-cy="Tsukiyomi"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Tsukiyomi')
		cy.get('.table-div').should('contain', 'Tsukiyomi Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Abyssal Wings')
	})
	it('adds all packs to the compendium', () => {
		cy.get('[data-cy="Ariadne"]').click()
		cy.get('[data-cy="Asterius"]').click()
		cy.get('[data-cy="Izanagi"]').click()
		cy.get('[data-cy="Kaguya"]').click()
		cy.get('[data-cy="Magatsu-Izanagi"]').click()
		cy.get('[data-cy="Messiah"]').click()
		cy.get('[data-cy="Orpheus"]').click()
		cy.get('[data-cy="Thanatos"]').click()
		cy.get('[data-cy="Tsukiyomi"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('.table-div').should('contain', 'Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne Picaro')
		cy.get('.table-div').should('contain', 'Asterius')
		cy.get('.table-div').should('contain', 'Asterius Picaro')
		cy.get('.table-div').should('contain', 'Izanagi Picaro')
		cy.get('.table-div').should('contain', 'Kaguya Picaro')
		cy.get('.table-div').should('contain', 'Magatsu-Izanagi Picaro')
		cy.get('.table-div').should('contain', 'Messiah Picaro')
		cy.get('.table-div').should('contain', 'Orpheus Picaro')
		cy.get('.table-div').should('contain', 'Thanatos Picaro')
		cy.get('.table-div').should('contain', 'Tsukiyomi Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Beast Weaver')
		cy.get('.table-div').should('contain', 'Titanomachia')
		cy.get('.table-div').should('contain', 'Cross Slash')
		cy.get('.table-div').should('contain', 'Shining Arrows')
		cy.get('.table-div').should('contain', 'Magatsu Mandala')
		cy.get('.table-div').should('contain', 'Oratorio')
		cy.get('.table-div').should('contain', 'Cadenza')
		cy.get('.table-div').should('contain', 'Door of Hades')
		cy.get('.table-div').should('contain', 'Abyssal Wings')
	})
	it.only('adds a pack then removes it', () => {
		cy.get('[data-cy="Ariadne"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('.table-div').should('contain', 'Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('contain', 'Beast Weaver')
		cy.get('[alt="DLC Settings"').click()
		cy.get('[data-cy="Ariadne"]').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('.table-div').should('not.contain', 'Ariadne')
		cy.get('.table-div').should('not.contain', 'Ariadne Picaro')
		cy.get('[alt="Skill List"]').click()
		cy.get('.table-div').should('not.contain', 'Beast Weaver')
	})
})
