describe('DLC Settings', () => {
	beforeEach(() => {
		cy.visit('/p5/settings')
	})
	it('adds Ariadne to the compendium', () => {
		cy.get('#Ariadne').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne Picaro')
	})
	it('adds Asterius to the compendium', () => {
		cy.get('#Asterius').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Asterius')
		cy.get('.table-div').should('contain', 'Asterius')
		cy.get('.table-div').should('contain', 'Asterius Picaro')
	})
	it('adds Izanagi to the compendium', () => {
		cy.get('#Izanagi').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Izanagi')
		cy.get('.table-div').should('contain', 'Izanagi Picaro')
	})
	it('adds Kaguya to the compendium', () => {
		cy.get('#Kaguya').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Kaguya')
		cy.get('.table-div').should('contain', 'Kaguya Picaro')
	})
	it('adds Magatsu-Izanagi to the compendium', () => {
		cy.get('#Magatsu-Izanagi').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Magatsu-Izanagi')
		cy.get('.table-div').should('contain', 'Magatsu-Izanagi Picaro')
	})
	it('adds Messiah to the compendium', () => {
		cy.get('#Messiah').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Messiah')
		cy.get('.table-div').should('contain', 'Messiah Picaro')
	})
	it('adds Orpheus to the compendium', () => {
		cy.get('#Orpheus').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Orpheus')
		cy.get('.table-div').should('contain', 'Orpheus Picaro')
	})
	it('adds Thanatos to the compendium', () => {
		cy.get('#Thanatos').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Thanatos')
		cy.get('.table-div').should('contain', 'Thanatos Picaro')
	})
	it('adds Tsukiyomi to the compendium', () => {
		cy.get('#Tsukiyomi').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('[placeholder="Ex. Mara"]').click().type('Tsukiyomi')
		cy.get('.table-div').should('contain', 'Tsukiyomi Picaro')
	})
	it('adds all packs to the compendium', () => {
		cy.get('#Ariadne').click()
		cy.get('#Asterius').click()
		cy.get('#Izanagi').click()
		cy.get('#Kaguya').click()
		cy.get('#Magatsu-Izanagi').click()
		cy.get('#Messiah').click()
		cy.get('#Orpheus').click()
		cy.get('#Thanatos').click()
		cy.get('#Tsukiyomi').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('.table-div').should('contain', 'Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne Picaro')
		cy.get('.table-div').should('contain', 'Asterius')
		cy.get('.table-div').should('contain', 'Asterius Picaro')
		cy.get('.table-div').should('contain', 'Izanagi Picaro')
		cy.get('.table-div').should('contain', 'Kaguya Picaro')
		cy.get('.table-div').should('contain', 'Magatsu-Izanagi Picaro')
		cy.get('.table-div').should('contain', 'Messiah Picaro')
		cy.get('.table-div').should('contain', 'Orpheus Picaro')
		cy.get('.table-div').should('contain', 'Thanatos Picaro')
		cy.get('.table-div').should('contain', 'Tsukiyomi Picaro')
	})
	it('adds a pack then removes it', () => {
		cy.get('#Ariadne').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('.table-div').should('contain', 'Ariadne')
		cy.get('.table-div').should('contain', 'Ariadne Picaro')
		cy.get('[alt="DLC Settings"').click()
		cy.get('#Ariadne').click()
		cy.get('[alt="Persona List"]').click()
		cy.get('.table-div').should('not.contain', 'Ariadne')
		cy.get('.table-div').should('not.contain', 'Ariadne Picaro')
	})
})
